### ISSUE TITLE
[Patcher] sed:1

### ISSUE THREAD

**Issue by MrBenFTW** [jakeajames/rootlessJB3#1]
Command I enter: `./patcher cylinder_1.0.6.deb Cylinder`

What happens?
 A folder named `Cylinder` is created. 

Output:
`sed: 1: "/tmp/_ENTS.plist": invalid command code _`

**Comment by jakeajames** [comment]
Fixed

**Comment by Co2333** [comment]
./patcher /Users/lakr/Downloads/videohud_2.3.deb ./VideoHUD
./patcher: line 52: [: ==: unary operator expected
sed: 1: "/tmp/_ENTS.plist": invalid command code _
./patcher: line 49: 16757 Abort trap: 6           ldid -S/tmp/_ENTS.plist $2 2> /dev/null

Still happens.
